-- Insert fun JKT48 fan experience options
INSERT INTO options (name) VALUES
  ('Verif Theater terus tapi Row J'),
  ('Verif 2 bulan sekali tapi Row A terus'),
  ('Dapat MnG tapi lupa mau ngomong apa'),
  ('Dapat video call tapi koneksi lag'),
  ('Dapat handshake tapi keringat dingin'),
  ('Dapat 2s tapi mata kedip'),
  ('Dapat tiket theater tapi macet total'),
  ('Dapat verif tapi lupa bawa KTP'),
  ('Dapat 2-shot tapi baju ketumpahan minuman'),
  ('Dapat theater tapi Kursi B1'),
  ('Dapat verif tapi salah tulis nama'),
  ('Dapat tiket konser tapi sakit'),
  ('Dapat 2-shot tapi pose awkward'),
  ('Dapat theater tapi ketiduran dirumah'),
  ('Dapat meet & greet tapi telat'),
  ('Dapat foto bareng tapi blur'),
  ('Verif terus tapi uang pas-pasan'),
